name: "CI"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.x", "18.x"]

    steps:
      - uses: actions/checkout@v4
        name: "🛒 Checkout code"

      - name: "🔧 Set up Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "📦 Install pnpm"
        run: npm install -g pnpm

      - name: "🚀 Install dependencies"
        run: pnpm install

      - name: "🔍 Lint code"
        run: pnpm run lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.x", "18.x"]

    steps:
      - uses: actions/checkout@v4
        name: "🛒 Checkout code"

      - name: "🔧 Set up Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "📦 Install pnpm"
        run: npm install -g pnpm

      - name: "🚀 Install dependencies"
        run: pnpm install

      - name: "🏗️ Build"
        run: pnpm run build
